### ISSUE TITLE
sometimes crashes on scrape

### ISSUE THREAD

**Issue by jstoebel** [jstoebel/kata_scrape#9]
```
scraping descriptionTraceback (most recent call last):
  File "/Users/stoebelj/.virtualenvs/codewars/bin/kata-scrape", line 4, in <module>
    kata_scrape.main()
  File "/Users/stoebelj/.virtualenvs/codewars/lib/python3.6/site-packages/kata_scrape/main.py", line 66, in main
    fetch(args)
  File "/Users/stoebelj/.virtualenvs/codewars/lib/python3.6/site-packages/kata_scrape/main.py", line 60, in fetch
    c.make_kata()
  File "/Users/stoebelj/.virtualenvs/codewars/lib/python3.6/site-packages/kata_scrape/client.py", line 73, in make_kata
    self._scrape_description()
  File "/Users/stoebelj/.virtualenvs/codewars/lib/python3.6/site-packages/kata_scrape/client.py", line 103, in _scrape_description
    descrip = soup.select('#description')[0]
IndexError: list index out of range
```

**Comment by jstoebel** [comment]
first guess: the dom isn't fully ready when selenium goes to pull the data.

**Comment by jstoebel** [comment]
fixed!
